export const ANNOTATION_NAME_REGEX = /@([A-Za-z][A-Za-z0-9_]*)/g;

export const ANNOTATION_PARAMS_REGEX = /\(\s*((?:[^()]*|\([^()]*\))*)\s*\)/;

export const ANNOTATION_PARAMS_SPLIT_REGEX = /,(?![^{]*})/;

export const PRISMA_SCALAR: Record<string, string> = {
    String: 'string',
    Boolean: 'boolean',
    Int: 'number',
    BigInt: 'bigint',
    Float: 'number',
    Decimal: 'Prisma.Decimal',
    DateTime: 'Date',
    Bytes: 'Buffer',
    Json: 'Prisma.JsonValue',
    Object: '{ [key: string]: any }'
};

export const PRISMA_SCALAR_TYPE: Record<string, string> = {
    ...PRISMA_SCALAR,
    Decimal: 'number',
    DateTime: '() => Date',
    Bytes: '() => Buffer',
    Json: '() => Object',
    Object: '() => Object'
};

export const PRISMA_SCALAR_FORMAT: Record<string, { type: string; format?: string }> = {
    String: { type: 'string' },
    Boolean: { type: 'boolean' },
    Int: { type: 'integer', format: 'int32' },
    BigInt: { type: 'integer', format: 'int64' },
    Float: { type: 'number', format: 'float' },
    Decimal: { type: 'string', format: 'Decimal.js' },
    DateTime: { type: 'string', format: 'date-time' }
};

export const SWAGGER_DECORATORS = ['ApiHideProperty', 'ApiProperty', 'ApiPropertyOptional', 'ApiPropertyRequired', 'ApiExtraModels'];

export const SWAGGER_API_PROPERTY_DECORATORS = ['description', 'minimum', 'maximum', 'exclusiveMinimum', 'exclusiveMaximum', 'minLength', 'maxLength', 'minItems', 'maxItems', 'example'];

export const CLASS_TRANSFORMER_DECORATORS = ['Type', 'Transform'];

export const CLASS_VALIDATOR_DECORATORS = [
    'Allow',
    'ArrayContains',
    'ArrayMaxSize',
    'ArrayMinSize',
    'ArrayNotContains',
    'ArrayNotEmpty',
    'ArrayUnique',
    'Contains',
    'Equals',
    'IsAlpha',
    'IsAlphanumeric',
    'IsArray',
    'IsAscii',
    'IsBIC',
    'IsBase32',
    'IsBase58',
    'IsBase64',
    'IsBoolean',
    'IsBooleanString',
    'IsBtcAddress',
    'IsByteLength',
    'IsCreditCard',
    'IsCurrency',
    'IsDataURI',
    'IsDate',
    'IsDateString',
    'IsDecimal',
    'IsDefined',
    'IsDivisibleBy',
    'IsEAN',
    'IsEmail',
    'IsEmpty',
    'IsEthereumAddress',
    'IsFQDN',
    'IsFirebasePushId',
    'IsFullWidth',
    'IsHash',
    'IsHSLColor',
    'IsHexadecimal',
    'IsIBAN',
    'IsISIN',
    'IsISO31661Alpha2',
    'IsISO31661Alpha3',
    'IsISO4217CurrencyCode',
    'IsISO8601',
    'IsISRC',
    'IsISSN',
    'IsIdentityCard',
    'IsImage',
    'IsIn',
    'IsInstance',
    'IsInt',
    'IsIP',
    'IsISBN',
    'IsIsHalfWidth',
    'IsIsHexColor',
    'IsIsVariableWidth',
    'IsJWT',
    'IsJSON',
    'IsLatLong',
    'IsLatitude',
    'IsLocale',
    'IsLongitude',
    'IsLowercase',
    'IsMACAddress',
    'IsMagnetURI',
    'IsMilitaryTime',
    'IsMimeType',
    'IsMobilePhone',
    'IsMongoId',
    'IsMultiByte',
    'IsNegative',
    'IsNotEmpty',
    'IsNotEmptyObject',
    'IsNotIn',
    'IsNumber',
    'IsNumberString',
    'IsObject',
    'IsOctal',
    'IsOptional',
    'IsPassportNumber',
    'IsPhoneNumber',
    'IsPort',
    'IsPositive',
    'IsPostalCode',
    'IsRFC3339',
    'IsRgbColor',
    'IsSemVer',
    'IsString',
    'IsStrongPassword',
    'IsSurrogatePair',
    'IsTaxId',
    'IsTimeZone',
    'IsUppercase',
    'IsUrl',
    'IsUUID',
    'Length',
    'Max',
    'MaxDate',
    'MaxLength',
    'Matches',
    'Min',
    'MinDate',
    'MinLength',
    'NotContains',
    'NotEquals',
    'ValidateIf',
    'ValidateNested'
];
